# Production configuration
apiServer:
  port: 8080
  publicHost: insomniabutler-alb-984929215.us-east-1.elb.amazonaws.com
  publicPort: 80
  publicScheme: http
database:
  host: insomniabutler-db.ccbsiy2ao0py.us-east-1.rds.amazonaws.com
  port: 5432
  name: insomniabutler
  user: postgres
  password: IHbiBtopMCFejyVmKPx3
  requireSsl: true
redis:
  enabled: false