name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    if: false
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.2'
      SERVERPOD_PASSWORD_database: ${{ secrets.DATABASE_PASSWORD }}
      SERVERPOD_PASSWORD_redis: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: insomniabutler_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: insomniabutler_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: insomniabutler_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: insomniabutler_server
        run: serverpod generate

      - name: Run tests
        working-directory: insomniabutler_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: insomniabutler_server
        run: docker compose down -v
